# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='enderecoStr',
            field=models.CharField(default='vazio', max_length=250, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='T\xedtulo'),
        ),
    ]
