# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20160526_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='enderecoStr',
            field=models.CharField(default='vazio', max_length=250, verbose_name='Endere\xe7o'),
        ),
    ]
