# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20160526_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='parcela',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG')], default='CPF', max_length=1),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Trabalho', 'Trabalho'), ('Comercial', 'Comercial')], default='Residencial', max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Trabalho', 'Trabalho'), ('Comercial', 'Comercial')], default='Residencial', max_length=1),
        ),
    ]
