# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20160526_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
