# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20160526_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Animais', 'Animais'), ('Comidas', 'Comidas'), ('Eletrodomesticos', 'Eletrodomesticos'), ('Games', 'Games'), ('Livros', 'Livros'), ('Antiguidades', 'Antiguidades'), ('Veiculos', 'Ve\xedculos'), ('Musica', 'M\xfasica'), ('Outros', 'Outros')], default='Outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='fotos/produtos/produto.png', upload_to='fotos/produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], default='novo', max_length=20),
        ),
    ]
